type=item
matchItems=crossbow
nbt.display.Name=ipattern:*crimson codex*
model=./crimson_codex_closed
model.crossbow_pulling_0=crimson_codex_partial
model.crossbow_pulling_1=crimson_codex_partial2
model.crossbow_pulling_2=crimson_codex3
model.crossbow_arrow=crimson_codex2
model.crossbow_firework=crimson_codex2